# Generated by Django 4.1 on 2022-09-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0010_remove_table_is_payed_alter_menu_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('amount', models.IntegerField(verbose_name='مقدار به تومان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('amount', models.IntegerField(verbose_name='مقدار به تومان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('unit', models.CharField(choices=[('one_gr', 'یک گرم'), ('one_kg', 'یک کیلوگرم'), ('one_spoon', 'یک قاشق'), ('one_p', 'یک پیمانه'), ('other', 'دیگر')], max_length=20, verbose_name='واحد')),
                ('unit_price', models.IntegerField(verbose_name='قیمت تقریبی هر واحد')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('amount', models.IntegerField(verbose_name='مقدار به تومان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('payment_period', models.CharField(choices=[('day', 'هر روز'), ('week', 'هر هفته'), ('month', 'هر ماه'), ('three_month', 'هر سه ماه'), ('six_month', 'هر شش ماه'), ('year', 'هر سال')], max_length=15, verbose_name='دوره پرداخت')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('amount', models.IntegerField(verbose_name='مقدار به تومان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('payment_period', models.CharField(choices=[('day', 'هر روز'), ('week', 'هر هفته'), ('month', 'هر ماه'), ('three_month', 'هر سه ماه'), ('six_month', 'هر شش ماه'), ('year', 'هر سال')], max_length=20, verbose_name='دوره پرداخت')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.TextField(verbose_name='مواد لازم')),
                ('total_price', models.IntegerField(verbose_name='قیمت کل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.order', verbose_name='نام سفارش')),
            ],
        ),
    ]
