# Generated by Django 4.1 on 2022-10-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cost', '0004_periodiccost_date_alter_cost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodiccost',
            old_name='date',
            new_name='first_pay_date',
        ),
        migrations.AddField(
            model_name='periodiccost',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
