# Generated by Django 4.1 on 2022-10-16 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cost', '0005_rename_date_periodiccost_first_pay_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodiccost',
            old_name='reminder_of_Payment',
            new_name='reminder_of_payment',
        ),
        migrations.AddField(
            model_name='periodicincome',
            name='first_receive_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ اولین دریافت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodicincome',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='پایان یافته است'),
        ),
        migrations.AlterField(
            model_name='periodiccost',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='پایان یافته است'),
        ),
        migrations.AlterField(
            model_name='periodiccost',
            name='payment_period',
            field=models.CharField(choices=[('day', 'هر روز'), ('week', 'هر هفته'), ('month', 'هر ماه'), ('three_month', 'هر سه ماه'), ('six_month', 'هر شش ماه'), ('year', 'هر سال'), ('all', 'همه')], max_length=15, verbose_name='دوره پرداخت'),
        ),
        migrations.AlterField(
            model_name='periodicincome',
            name='payment_period',
            field=models.CharField(choices=[('day', 'هر روز'), ('week', 'هر هفته'), ('month', 'هر ماه'), ('three_month', 'هر سه ماه'), ('six_month', 'هر شش ماه'), ('year', 'هر سال'), ('all', 'همه')], max_length=20, verbose_name='دوره پرداخت'),
        ),
    ]
