# Generated by Django 4.1 on 2022-10-16 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cost', '0006_rename_reminder_of_payment_periodiccost_reminder_of_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicincome',
            name='payment_period',
        ),
        migrations.AddField(
            model_name='periodicincome',
            name='receive_period',
            field=models.CharField(choices=[('day', 'هر روز'), ('week', 'هر هفته'), ('month', 'هر ماه'), ('three_month', 'هر سه ماه'), ('six_month', 'هر شش ماه'), ('year', 'هر سال'), ('all', 'همه')], default=django.utils.timezone.now, max_length=20, verbose_name='دوره دریافت'),
            preserve_default=False,
        ),
    ]
