# Generated by Django 4.1 on 2022-08-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('price', models.CharField(max_length=1000, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('info', models.TextField(verbose_name='اطلاعات')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.category')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('info', models.TextField(verbose_name='اطلاعات')),
                ('is_active', models.BooleanField(default=True)),
                ('is_payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('total_price', models.CharField(max_length=1000, verbose_name='قیمت کل')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.menu')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.table')),
            ],
        ),
    ]
