# Generated by Django 4.1 on 2022-09-02 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='Order.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
    ]
