# Generated by Django 4.1 on 2022-09-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='table',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
