# Generated by Django 4.1 on 2022-09-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0005_remove_menu_cat_delete_order_remove_pay_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('table', models.CharField(max_length=200)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('info', models.TextField(verbose_name='اطلاعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_payed', models.BooleanField(default=False, verbose_name='پرداخت شده')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.table')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('price', models.CharField(max_length=1000, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('info', models.TextField(verbose_name='اطلاعات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.category')),
            ],
        ),
    ]
