# Generated by Django 4.1 on 2022-09-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
