# Generated by Django 4.1 on 2022-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='pay',
            name='products_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pay',
            name='total_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
