# Generated by Django 4.1 on 2022-09-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_rename_products_id_pay_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_payed',
        ),
        migrations.AlterField(
            model_name='menu',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده است'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='آماده است'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=2000, verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.CharField(max_length=200, verbose_name='میز'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='products',
            field=models.CharField(max_length=1000, verbose_name='سفارشات'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='success',
            field=models.BooleanField(default=False, verbose_name='پرداخت موفق'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.table', verbose_name='میز'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='total_price',
            field=models.CharField(max_length=100, verbose_name='قیمت کل'),
        ),
    ]
