# Generated by Django 4.1 on 2022-10-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_remove_table_is_payed_alter_menu_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('unit', models.CharField(choices=[('one_gr', 'یک گرم'), ('one_kg', 'یک کیلوگرم'), ('one_spoon', 'یک قاشق'), ('one_p', 'یک پیمانه'), ('other', 'دیگر')], max_length=20, verbose_name='واحد')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت تقریبی هر واحد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.TextField(verbose_name='مواد لازم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='طرز تهیه')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.menu', verbose_name='نام سفارش')),
            ],
        ),
    ]
