# Generated by Django 4.1 on 2022-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_material_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit_amount',
            field=models.FloatField(default=1, verbose_name='مقدار(بر حسب واحد)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('one_gr', 'گرم'), ('one_kg', 'کیلوگرم'), ('one_spoon', 'قاشق'), ('one_p', 'پیمانه'), ('other', 'دیگر')], max_length=20, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت تقریبی هر واحد'),
        ),
    ]
