# Generated by Django 4.1 on 2022-10-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_material_unit_amount_alter_material_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unit_amount',
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت هر واحد'),
        ),
    ]
