# Generated by Django 4.1 on 2022-12-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_remove_material_unit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت هر واحد به تومان'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='نام'),
        ),
    ]
