# Generated by Django 4.1 on 2022-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_m_alter_material_name_alter_material_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='bool',
            field=models.BooleanField(default=True),
        ),
    ]
