# Generated by Django 4.1 on 2022-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_m_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m',
            name='bool',
        ),
        migrations.AddField(
            model_name='m',
            name='bool2',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
