# Generated by Django 4.1 on 2022-12-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_remove_m_bool_m_bool2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m',
            name='name',
        ),
    ]
