# Generated by Django 4.1 on 2022-12-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_remove_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='name',
            field=models.CharField(default='l', max_length=10000, unique=True),
            preserve_default=False,
        ),
    ]
