# Generated by Django 4.1 on 2022-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='text',
            field=models.TextField(default='jj'),
            preserve_default=False,
        ),
    ]
