# Generated by Django 4.1 on 2022-12-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_m_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M',
        ),
    ]
