# Generated by Django 4.1 on 2022-12-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_delete_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date2', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=10000, unique=True)),
                ('text', models.TextField()),
                ('bool2', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.TextField()),
                ('date3', models.DateTimeField(auto_now_add=True)),
                ('date4', models.DateTimeField()),
            ],
        ),
    ]
