# Generated by Django 4.1 on 2022-12-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_alter_m_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='m',
            name='date3',
        ),
        migrations.RemoveField(
            model_name='m',
            name='date4',
        ),
    ]
