# Generated by Django 4.1 on 2022-12-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0023_remove_m_date2_remove_m_date3_remove_m_date4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m',
            old_name='date',
            new_name='date1',
        ),
    ]
