# Generated by Django 4.1 on 2022-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0026_alter_m_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m',
            name='date1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
